# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-15 07:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20170621_0309'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.CharField(default='Address here pls', max_length=200),
            preserve_default=False,
        ),
    ]
