# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-21 03:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='books',
            old_name='no_of_pages',
            new_name='price',
        ),
    ]
