# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-25 11:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20170621_0329'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='varification',
            field=models.BooleanField(default=False),
        ),
    ]
